[package]
name = "gui-exploration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.32.0"
x11 = { version = "2.20.1", features = ["xlib", "xft", "xrender", "glx"] }
